include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - prefer_relative_imports
    - require_trailing_commas

analyzer:
  exclude:
    - '**.g.dart'
    - '**.gr.dart'
    - '**.config.dart'
